"""make proposed_weight nullable (no-draft vs zero)

Revision ID: 0a25e34ff6b9
Revises: 6e8a3196b7d5
Create Date: 2026-07-07 15:30:25.692201
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '0a25e34ff6b9'
down_revision: Union[str, None] = '6e8a3196b7d5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    op.alter_column('client_managers', 'proposed_weight',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=True)
    # Existing rows were backfilled with 0.0 by the earlier migration, but that
    # 0 was a placeholder default, not a user-saved draft. Reset those to NULL
    # so the /portfolio overlay treats them as "no draft" (proposed==current)
    # rather than a deliberate 0% proposed weight.
    op.execute("UPDATE client_managers SET proposed_weight = NULL "
               "WHERE proposed_weight = 0")


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('client_managers', 'proposed_weight',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=False)
    # ### end Alembic commands ###
