"""add proposed_weight and style_buckets to client_managers

Revision ID: 6e8a3196b7d5
Revises: 58dc9bb41e2b
Create Date: 2026-07-07 14:21:27.643974
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision: str = '6e8a3196b7d5'
down_revision: Union[str, None] = '58dc9bb41e2b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # proposed_weight is NOT NULL, but existing rows have no value — add it with
    # a server_default of 0 so the backfill succeeds, then drop the default so
    # the app layer stays the single source of the value going forward.
    op.add_column(
        'client_managers',
        sa.Column('proposed_weight', sa.Float(), nullable=False, server_default='0'),
    )
    op.alter_column('client_managers', 'proposed_weight', server_default=None)
    op.add_column(
        'client_managers',
        sa.Column('style_buckets', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    )


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('client_managers', 'style_buckets')
    op.drop_column('client_managers', 'proposed_weight')
    # ### end Alembic commands ###
